name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📦 Checkout code
      uses: actions/checkout@v2

    - name: 🐍 Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: 📥 Install dependencies
      run: |
        pip install -r segmentation_project/requirements.txt

    - name: 🔓 Make start.sh executable
      run: chmod +x segmentation_project/start.sh

    - name: 🔐 Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 🚀 Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: segmentation-api-remy
        package: segmentation_project
